apiVersion: helm.sh/v1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 56.6.1
  values:
    grafana:
      adminPassword: "admin"
      service:
        type: ClusterIP
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false