apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - trading-engine
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: trading-engine
          image: trading-engine:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080