apiVersion: v1
kind: Service
metadata:
  name: trading-engine
spec:
  selector:
    app: trading-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000  # update if needed
  type: ClusterIP