apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - fe-app
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: fe-app
          image: fe-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000