apiVersion: v1
kind: Service
metadata:
  name: fe-app
spec:
  selector:
    app: fe-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080  # App port
    - protocol: TCP
      name: metrics
      port: 8000
      targetPort: 8000  # Metrics port
  type: ClusterIP