name: CPP SAST + SBOM

on:
  push:
    paths:
      - 'src/cpp-trading-engine/**'
  pull_request:
    paths:
      - 'src/cpp-trading-engine/**'
  workflow_dispatch:

jobs:
  sast-sbom:
    runs-on: ubuntu-latest
    name: Run SAST and generate SBOM

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        run: |
          docker build -f docker/cpp-trading-engine/Dockerfile -t hft-cpp-scan .

      - name: Trivy SAST + SBOM
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hft-cpp-scan
          format: 'table'
          scan-type: 'image'
          output: trivy-sbom-report.txt
          severity: 'CRITICAL,HIGH'

      - name: Grype SBOM Scan
        uses: anchore/scan-action@v3
        with:
          image: hft-cpp-scan
          acs-report-enable: true
          output-format: table

      - name: Upload Trivy SBOM Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: trivy-sbom-report.txt
