name: Build and Deploy C++ App to GKE

on:
  push:
    branches: [main]
    # paths:
    #   - '**.cpp'
    #   - 'CMakeLists.txt'
    #   - '.github/workflows/cpp.yml'
  pull_request:
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: hft-cpp
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hft-cpp
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++

      - name: Configure CMake
        run: |
          cd src/cpp-trading-engine
          cmake -S . -B build

      - name: Build app
        run: |
          cd src/cpp-trading-engine
          cmake --build build

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f docker/fe/Dockerfile -t $IMAGE_TAG .
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Push Docker image
      #   run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hft-cpp:latest

      # - name: Auth to GCP
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      # - name: Get GKE credentials
      #   uses: google-github-actions/get-gke-credentials@v2
      #   with:
      #     cluster_name: ${{ secrets.GKE_CLUSTER }}
      #     location: ${{ secrets.GKE_ZONE }}
      #     project_id: ${{ secrets.GCP_PROJECT }}

      # - name: Deploy canary release
      #   run: |
      #     kubectl set image deployment/hft-cpp-canary hft-cpp=$IMAGE_TAG
      #     kubectl rollout status deployment/hft-cpp-canary

      # - name: Wait & verify canary
      #   run: sleep 60  # or run health checks here

      # - name: Promote canary to primary
      #   run: |
      #     kubectl set image deployment/hft-cpp-primary hft-cpp=$IMAGE_TAG
      #     kubectl rollout status deployment/hft-cpp-primary
