name: CPP Dependencies & Dockerfile

on:
  pull_request:
    paths:
      - 'src/cpp-trading-engine/**'
      - 'docker/cpp-trading-engine/**'
  workflow_dispatch:

jobs:
  deps-dockerfile-scan-cpp:
    name: C++ Dependency + Dockerfile Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trivy Dockerfile Scan (C++)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: ./docker/cpp-trading-engine/
          format: 'table'
          output: trivy-cpp-dockerfile-report.txt

      - name: Upload C++ Dockerfile Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-cpp-dockerfile-report
          path: trivy-cpp-dockerfile-report.txt
