name: Frontend Python CI/CD

on:
  push:
    branches: [main]
  pull_request:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: fe-app
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fe-app

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:$GITHUB_SHA .

    - name: Push image to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push $IMAGE_NAME:$GITHUB_SHA

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        sed -i "s|__TAG__|$GITHUB_SHA|" k8s/fe-deployment.yaml
        kubectl apply -f k8s/fe-deployment.yaml