name: Frontend Python CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: fe-app
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fe-app
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.11'

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     cd src/fe
    #     pip install -r requirements.txt

    # - name: Run tests
    #   run: pytest tests/

    - name: Set IMAGE_TAG
      run: |
        echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ github.run_number }}" >> $GITHUB_ENV
        echo "LATEST_TAG=${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV


    - name: Build Docker image
      run: docker build -f docker/fe/Dockerfile -t $IMAGE_TAG -t $LATEST_TAG .
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
          docker push $IMAGE_TAG
          docker push $LATEST_TAG    # - name: Set up GKE credentials
    #   uses: google-github-actions/get-gke-credentials@v1
    #   with:
    #     cluster_name: ${{ env.GKE_CLUSTER }}
    #     location: ${{ env.GKE_ZONE }}
    #     project_id: ${{ env.PROJECT_ID }}

    # - name: Deploy to GKE
    #   run: |
    #     sed -i "s|__TAG__|$GITHUB_SHA|" k8s/fe-app/deployment.yaml
    #     kubectl apply -f k8s/fe-app/deployment.yaml